### ISSUE TITLE
9.x compatibility planned?

### ISSUE THREAD

**Issue by pixelplumber** [ffrewer/frsupersized#3]
Hi, love this plugin for creating full-screen slideshows on smart-tvs in a couple of showrooms.  Wondered if you plan a 9.x LTS update now that it is out?  Was going to try my hand at getting it to work but not a developer so could be a slow process.

Thanks for a great plugin!

**Comment by pixelplumber** [comment]
I have got this working in 9.5 with only changes to em_conf.php TYPO3 versions and some playing around with jquery library versions.  The only issue I get is that when loading the plugin flexform the BE gives me about 24 PHP warnings:

> PHP Warning
Core: Error handler (BE): PHP Warning: count(): Parameter must be an array or an object that implements Countable in /home/--domain--/public_html/typo3/sysext/backend/Classes/Form/Element/CheckboxElement.php line 94

A bit of googling shows this to be a [php 7.2 change](http://php.net/manual/en/migration72.incompatible.php)? 

Not a programmer, but a bit of searching and my best guess is that its the [getSelectOrCheckbox](https://github.com/ffrewer/frsupersized/blob/db188a4e1c0da97aea477bed09fe3ab371c88ce7/Configuration/FlexForms/flexform_supersized.xml#L392) userfunc in the flexform code that calls a function that [returns a string](https://github.com/ffrewer/frsupersized/blob/db188a4e1c0da97aea477bed09fe3ab371c88ce7/Classes/Utility/TceFunc.php#L47) and not an array or countable object expected by the [checkbox element in the BE sysext](https://github.com/TYPO3/TYPO3.CMS/blob/bd0230437a1bd2ad3d7b25e3899d0a53ab41c50d/typo3/sysext/backend/Classes/Form/Element/CheckboxElement.php#L94)?

I think this is beyond my skill at the moment to know how to fix.  In any case the slider is working on the FE for me.

Thanks again, hope this helps.

**Comment by ffrewer** [comment]
Should be fixed now (v1.2.0dev). Please test it. 

Which jquery library versions did you use?
I have got some js errors too (incompatibility between jquery v 3.3.1 and the supersized core js) and used this settings to fix it:
plugin.tx_frsupersized.settings.general.jQueryFile = https://code.jquery.com/jquery-2.2.4.min.js
plugin.tx_frsupersized.settings.general.jQueryEasingFile = https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js

**Comment by pixelplumber** [comment]
Hi ffrewer, this is working well!

I also found that I had to use the old 1.x jquery with included easing, or engineer a 404 against the easing file in order for it to load.  Your constants though are working for me too.

Thanks very much.

**Comment by ffrewer** [comment]
Thanks for testing
